apiVersion: v1
kind: Pod
metadata:
  name: annotationpod
  annotations:
    owner: "EAA"
    notification-email: "admin@k8sfundamentals.com"
    releasedate: "06.10.2023"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  containers:
  - name: annotationcontainer
    image: nginx
    ports:
    - containerPort: 80