- name: create a user using a variable
  hosts: all
  become: true
  vars:
    user: sare
    ansible_ssh_private_key_file: "/home/ec2-user/test_pair.pem"
  tasks:
    - name: create a user {{ user }}
      ansible.builtin.user:
        name: "{{ user }}"