- name: show ipaddress in facts
  hosts: all
  tasks: 
    - name: show IP address
      ansible.builtin.debug:
        msg: > 
          This IP address {{ ansible_facts.default_ipv4.address }} is using by host
          