- name: Apache installation and configuration for ubuntuservers
  hosts: ubuntuservers
  tasks:
    - name: installing Apache
      ansible.builtin.apt:
        name: apache2
        state: latest

    - name: index.html
      ansible.builtin.copy:
        content: "<h1> Hello everyone from EAA </h1>"
        dest: /var/www/html/index.html

    - name: restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted
        enabled: yes


- name: Apache installation and configuration for webservers
  hosts: webservers
  tasks:
    - name: installing httpd and wget
      ansible.builtin.yum:
        pkg: "{{ item }}"
        state: present
      loop:
        - httpd
        - wget